library(rCharts)
library(LDAvis)
library(shinyjs)
library(DT)
library(collapsibleTree)

shinyUI(fluidPage(
  useShinyjs(),
  fluidRow(column(3,
                  sidebarPanel(width = 12,
                               radioButtons(inputId = "usermode", label = "Select user mode", choices = c("Pre-Loaded", "Basic", "Advanced"), selected = "Pre-Loaded"),
                               conditionalPanel(condition="input.usermode=='Pre-Loaded'",
                                                uiOutput("ui_preloadmodlist")),
                               conditionalPanel(condition="input.usermode!='Pre-Loaded'",
                                                fileInput('saved_model_file', 'Load Existing Model?',
                                                          accept=c('RData'))),
                               conditionalPanel(condition="input.usermode=='Advanced'",
                                                tags$div(title = "Perform summary search first to find number of articles, then detailed search, then linkage search. Search results for list lengths > 1000 articles are not currently supported",titlePanel(title="Inputs")),
                               textInput("search_text", "Search Terms (Boolean Operators Accepted)"),
                               radioButtons("database", "Choose Database For Search", c("Load Model", "pubmed", "PLOS", "aRxiv", "OPS patents", "Local Files", "CSV File"), selected = "Load Model"),
                               conditionalPanel(condition="input.database=='Local Files'",
                                                actionButton("local_filepath", "Select Local File Directory"),
                                                textOutput("chosenlocalPath"),
                                                radioButtons("locallinkby", "Choose File Property to Use For Reference Linking", c("None", "Filename"), selected = "None")),
                               conditionalPanel(condition="input.database=='CSV File'",
                                                fileInput("csv_input", label = "Select CSV File", accept = c(
                                                  "text/csv",
                                                  "text/comma-separated-values,text/plain",
                                                  ".csv"))),
                               #actionButton("local_filepath", "Select Local File Directory"),
                               #textOutput("chosenlocalPath"),
                               #radioButtons("locallinkby", "Choose File Property to Use For Reference Linking", c("None", "Filename"), selected = "None"),
                               actionButton("summary_search", "Perform Summary Search"),
                               hr(),
                               # fileInput("csv_input", label = "Select CSV File", accept = c(
                               #   "text/csv",
                               #   "text/comma-separated-values,text/plain",
                               #   ".csv")),
                               textOutput("summary_search_results"),
                               hr(),
                               actionButton("detailed_search", "Get Detailed Article Information"),
                               textOutput("detailed_search_results"),
                               hr(),
                               actionButton("link_search", "Perform Linkage Search"),
                               actionButton("include_citedby", "Include Articles Citing This Collection"),
                               actionButton("include_referencedby", "Include Articles Referenced by This Collection"),
                               textOutput("link_search_results"),
                               hr(),
                               h4("Augment Data From Additional CSV File"),
                               fileInput("augment_input", label = "Select CSV File", accept = c(
                                 "text/csv",
                                 "text/comma-separated-values,text/plain",
                                 ".csv")),
                               uiOutput("ui_augmentkey"),
                               uiOutput("ui_dbkey"),
                               uiOutput("ui_augmentnew"),
                               actionButton("augment_button", label = "Add Augmented Data"),
                               radioButtons("usemultiword", "Find Multiword Tokens?", c("Yes", "No"), selected = "Yes"),
                               radioButtons("usesentenceanalysis", "Run Sentence Analysis? (Experimental - Takes a Long Time)", c("Yes", "No"), selected = "No"),
                               hr(),
                               tags$div(title = "Save article list as csv file",
                                        textInput("ArticleSaveName","File Name For Article List:",value="ArticleSaveName")),
                               tags$div(title = "Save article list as csv file",
                                        downloadButton("ArticleSave","Save Article List")),
                               hr(),
                               tags$div(title = "Save topic model to reload from current state later",
                                        textInput("model_filename","File Name For Saved Model:",value="ModelSaveName")),
                               tags$div(title = "Save topic model to reload from current state later",
                                        downloadButton("ModelSave","Save Model")),
                               hr(),
                               numericInput(inputId = "stmtermminpercent", label = "Words Must Be In Min % of Documents", value = 1, min = 0, max = 100),
                               numericInput(inputId = "stmtermmaxpercent", label = "Words Cannot Be In More Than Max % of Documents", value = 99, min = 0, max = 100),
                               actionButton("gentopicmodelbutton", label = "Create Topic Model"),
                               actionButton("debug_button", "Enter R Code Browser"),
                               hr()
                               )

                  )
  ),
  column(9,navbarPage("Graphical Analysis",
                      tabPanel("Topic Map",
                               tags$div(title = "Full document text matching takes an entire sentence, paragraph, or document as input and tries to find the closest match based on the overall topic content of the search query. Cut and paste is supported.",
                                        h4("Full Document Text Matching", style = "display: inline-block"), tags$span(style="color:blue", "?")),
                               #textInput("similar_document", "Search for Documents that match the contents of this document"),
                               textAreaInput(inputId = "similar_document", label = "Search for Documents that match the contents of this document",
                                             placeholder = "Full text document matching works best with large searches. Try typing an entire sentence, paragraph, or pasting the entire contents of a document in this box."),
                               htmlOutput("TopicSemMatch"),
                               dataTableOutput("SemDocMatchTable"),
                               plotOutput("SemanticSearchTimePlot"),
                               h4(),
                               hr(),
                               tags$div(title = "Search for trends over time in key words or phrases. Search words or phrases can be plotted over time. To plot multiple phrases, enter each one individually, then click Plot Search Phrase to add the trend to the plot.",
                                        h4("Key Word/Phrase Trending", style = "display: inline-block"), tags$span(style="color:blue", "?")),
                               h4(),
                               textInput(inputId = "keyword_search", label = "Search for Topics Containing Specified Words or Phrases. To Search Using Multiple Phrases, Separate Phrases by Commas. Uses Regex matching logic: https://en.wikipedia.org/wiki/Regular_expression", placeholder = "Keyword search"),
                               htmlOutput("TopicFind"),
                               column(6,actionButton("plot_keyphrase", label = "Plot Search Phrase"),
                                      actionButton("clear_plot_keyphrase", label = "Clear Phrase Plot")),
                               plotOutput("KeywordTimePlot"),
                               h4(),
                               ###########################Old code with both elements on same page for when java conflict is fixed in topicPCA
                               #tags$div(title = "Hierarchy of topics. Click on nodes to combine or separate topics. Changes will propagate through other topic graphs.", h4("Topic Hierarchy")),
                               #collapsibleTreeOutput(outputId = "TopicTree"),
                               hr(),
                               tags$div(title = "Topic map of all articles in network map. Each topic is associated with a word list. Clicking on a topic circle will show the trend of the topic over time below this graph and will also cause the network graph at the top to apply transparency to the article nodes based on article relevance. Multiple topics can be selected at once.",
                                        h4("Topic Map of Article Abstracts", style = "display: inline-block"), tags$span(style="color:blue", "?")),
                               actionButton("cleartopics", "Clear Topic Selections"),
                               visOutput("TopicPCA"),
                               h4(),
                               # # ########################## Temporary code to display topicPCA and hierarchy in separate tabs - DOESN'T FIX CONFLICT
                               # navbarPage("Graphical Analysis",
                               #            tabPanel("Topic Hierarchy",
                               #                     tags$div(title = "Hierarchy of topics. Click on nodes to combine or separate topics. Changes will propagate through other topic graphs.", h4("Topic Hierarchy")),
                               #                     collapsibleTreeOutput(outputId = "TopicTree")),
                               #            tabPanel("Topic and Word Chart",
                               #                     visOutput("TopicPCA"))
                               #            ),
                               # ############################### End temporary code
                               #tauchartsOutput("TopicTime"),
                               tags$div(title = "Trend of the selected topics over time. The network graph at the top will apply transparency to the article nodes based on article relevance. Dotted lines represent 95% confidence intervals for the topic proportions. Multiple topics can be selected at once.",
                                        h4("Selected Topic Trend Over Time (With 95% Confidence Intervals)", style = "display: inline-block"), tags$span(style="color:blue", "?")),
                               plotOutput("TopicTime"),
                               hr(),
                               tags$div(title = "Most relevant sentences are selected by multiplying all selected topic probabilities with the entropy (information content) of each sentence (based on word count approximation).",
                                        h4("Most Relevant Sentences for Selected Topics", style = "display: inline-block"), tags$span(style="color:blue", "?")),
                               #textOutput("RelevantSentences"), #OBSOLETE, REPLACED BY RelevantSentencesDT
                               dataTableOutput("RelevantSentencesDT"),
                               #h4("Article Details"),
                               #verbatimTextOutput("clickedNode"),
                               #h4("Referenced By"),
                               #verbatimTextOutput("connectedNodes"),
                               ##TODO## Finish this data table below once javascript passing clicked nodes is done
                               #                                      h4("Clicked Node Data"),
                               #                                      dataTableOutput("nodeDataTable"),
                               h4()
                      ),
                      tabPanel("Article Network",
                               tags$div(title = "Network diagram of articles. References are conected by lines, nodes are sized by number of times cited",
                                        h4("Network", style = "display: inline-block"), tags$span(style="color:blue", "?")),
                               column(3,uiOutput("ui_CSVID")),
                               column(3,uiOutput("ui_CSVtext")),
                               column(3,uiOutput("ui_CSVarticletype")),
                               column(3,uiOutput("ui_CSVkeyword")),
                               h6(column(3,sliderInput("nodexspacing", label = "Horizontal Node Spacing", min = 0.1, max = 3, value = 1)),
                                  column(3,sliderInput("nodeyspacing", label = "Vertical Node Spacing", min = 0.1, max = 3, value = 1)),
                                  column(3,uiOutput("ui_graphlayout")),
                                  column(3,radioButtons("gennetgraph", "Generate Article Graph", c("Yes", "No"), selected = "No"))),
                               hr(),
                               hr(),
                               hr(),
                               hr(),
                               hr(),
                               hr(),
                               hr(),
                               rcytoscapejsOutput("plot",height="600px"),
                               hr(),
                               tags$div(title = "Click on keyword or article type name to highlight it in the network graph. Click on the 'Filter Results' button to filter the search results to only include the highlighted articles",
                                        h4("Keyword and Article Type Filters", style = "display: inline-block"), tags$span(style="color:blue", "?")),
                               column(6, actionButton("cleargroups", "Clear Group Selections")),
                               column(6, actionButton("filtergroups", "Include Only Selected Groups",  style='background:green; color:white'),
                                      actionButton("excludegroups", "Exclude All Selected Groups",  style='background:red; color:white'),
                                      actionButton("clear_filters", "Clear All Applied Filters")),
                               hr(),
                               column(6,
                                      showOutput("articletypebar", "highcharts")),
                               column(6,
                                      showOutput("keywordbar", "highcharts")
                               ))
  ))
  ))
)